<a href="https://colab.research.google.com/github/sw6820/kostat/blob/main/Ensemble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
cd /content/drive/MyDrive/Colab Notebooks/kostat

/content/drive/MyDrive/Colab Notebooks/kostat

In [3]:
import pandas as pd

In [ ]:
# predict_ensem = ensem['digit_3']
# predict_koelec = koelectra['digit_3']
# predict_roberta = roberta['digit_3']
# predict_bert = bert['digit_3']
# predict_gpt = kogpt2['digit_3']

In [4]:
answer = []

In [5]:
def ensemble(lst):
    lst = list(map(str, lst))
    count = 0
    mode = 0;
    for x in lst: 
        if lst.count(x) > count:
            count = lst.count(x)
            mode = x

    return mode

In [ ]:
def per(x, percent):
    x_list = []
    for i in range(percent):
      x_list.append(x)
    return x_list

In [ ]:
# def ensemble(lists):
#     all_list = sum(lists,[])
#     lst = list(map(str, all_list))
#     count = 0
#     mode = 0;
#     for x in lst: 
#         if lst.count(x) > count:
#             count = lst.count(x)
#             mode = x

#     return mode

In [6]:
bertbase = pd.read_csv('./ensemble/bert_base_space.csv')
bigbird = pd.read_csv('./ensemble/bigbird_epoch3_val0.9263.csv')
koelectra = pd.read_csv('./ensemble/koelectra-base_5epoch_89.78.csv')
kogpt2 = pd.read_csv('./ensemble/kogpt2_epoch3_3_87.81.csv')
robertabase = pd.read_csv('./ensemble/roberta-base_5epoch_val0.9262.csv')
robertasmall = pd.read_csv('./ensemble/roberta-small_5epoch_val0.9253.csv')
kfold = pd.read_csv('./ensemble/roberta-base_oof_5fold.csv')
test = pd.read_csv('./2. 모델개발용자료.txt', sep='|', encoding='cp949')
submission = pd.read_csv("./답안 작성용 파일 (3).csv", encoding='cp949')

In [ ]:
ensem['digit_3'].count()

100000

In [8]:
for i in range(0, len(bertbase['digit_3'])):
    answer.append(ensemble([bertbase['digit_3'][i],
                            bigbird['digit_3'][i],
                            koelectra['digit_3'][i],
                            kogpt2['digit_3'][i],
                            robertabase['digit_3'][i],
                            robertasmall['digit_3'][i],
                            kfold['digit_3'][i]]))

In [9]:
answer

['561',
 '466',
 '949',
 '302',
 '562',
 '181',
 '561',
 '259',
 '952',
 '953',
 '107',
 '961',
 '162',
 '862',
 '729',
 '961',
 '465',
 '472',
 '476',
 '721',
 '259',
 '478',
 '872',
 '969',
 '320',
 '951',
 '474',
 '682',
 '682',
 '912',
 '855',
 '463',
 '561',
 '251',
 '961',
 '561',
 '478',
 '620',
 '222',
 '862',
 '478',
 '181',
 '477',
 '562',
 '339',
 '521',
 '551',
 '464',
 '732',
 '471',
 '474',
 '107',
 '291',
 '561',
 '466',
 '969',
 '856',
 '320',
 '141',
 '162',
 '452',
 '259',
 '951',
 '382',
 '412',
 '952',
 '561',
 '941',
 '863',
 '478',
 '952',
 '681',
 '969',
 '953',
 '478',
 '855',
 '472',
 '961',
 '561',
 '902',
 '453',
 '561',
 '340',
 '474',
 '478',
 '452',
 '478',
 '969',
 '856',
 '952',
 '466',
 '467',
 '251',
 '292',
 '949',
 '862',
 '733',
 '463',
 '582',
 '422',
 '474',
 '463',
 '477',
 '473',
 '682',
 '721',
 '941',
 '961',
 '562',
 '872',
 '969',
 '862',
 '641',
 '969',
 '949',
 '422',
 '452',
 '474',
 '421',
 '732',
 '107',
 '292',
 '856',
 '471',
 '107',
 '562',
 '493',
 '631',
 '856',
 '961',
 '451',
 '842',
 '472',
 '561',
 '912',
 '969',
 '969',
 '478',
 '681',
 '856',
 '961',
 '475',
 '856',
 '681',
 '251',
 '471',
 '492',
 '561',
 '11',
 '561',
 '132',
 '852',
 '682',
 '961',
 '478',
 '262',
 '475',
 '465',
 '651',
 '682',
 '271',
 '107',
 '478',
 '421',
 '463',
 '912',
 '239',
 '561',
 '131',
 '856',
 '452',
 '466',
 '855',
 '852',
 '763',
 '855',
 '231',
 '682',
 '561',
 '551',
 '478',
 '474',
 '423',
 '292',
 '912',
 '561',
 '651',
 '561',
 '733',
 '851',
 '682',
 '869',
 '582',
 '466',
 '284',
 '467',
 '424',
 '856',
 '561',
 '463',
 '949',
 '478',
 '259',
 '474',
 '411',
 '855',
 '912',
 '682',
 '472',
 '682',
 '340',
 '721',
 '561',
 '492',
 '561',
 '856',
 '561',
 '251',
 '463',
 '562',
 '961',
 '463',
 '855',
 '251',
 '181',
 '271',
 '103',
 '561',
 '521',
 '561',
 '465',
 '466',
 '478',
 '857',
 '422',
 '712',
 '284',
 '762',
 '291',
 '292',
 '292',
 '729',
 '872',
 '949',
 '969',
 '464',
 '242',
 '961',
 '561',
 '953',
 '474',
 '641',
 '478',
 '107',
 '561',
 '472',
 '732',
 '259',
 '682',
 '464',
 '472',
 '872',
 '855',
 '862',
 '949',
 '561',
 '863',
 '478',
 '912',
 '561',
 '473',
 '729',
 '479',
 '471',
 '949',
 '662',
 '292',
 '272',
 '473',
 '856',
 '463',
 '424',
 '473',
 '474',
 '561',
 '472',
 '251',
 '856',
 '912',
 '561',
 '466',
 '562',
 '141',
 '969',
 '857',
 '561',
 '424',
 '424',
 '291',
 '912',
 '471',
 '561',
 '862',
 '463',
 '561',
 '451',
 '561',
 '424',
 '562',
 '292',
 '551',
 '681',
 '582',
 '339',
 '682',
 '620',
 '464',
 '423',
 '477',
 '952',
 '949',
 '476',
 '292',
 '953',
 '107',
 '424',
 '862',
 '561',
 '759',
 '561',
 '472',
 '969',
 '713',
 '465',
 '856',
 '949',
 '961',
 '682',
 '682',
 '465',
 '465',
 '682',
 '856',
 '466',
 '529',
 '464',
 '872',
 '742',
 '592',
 '422',
 '478',
 '351',
 '682',
 '422',
 '561',
 '467',
 '715',
 '969',
 '681',
 '639',
 '872',
 '582',
 '561',
 '494',
 '465',
 '949',
 '107',
 '472',
 '561',
 '478',
 '715',
 '478',
 '107',
 '641',
 '466',
 '467',
 '582',
 '561',
 '855',
 '239',
 '733',
 '339',
 '682',
 '721',
 '521',
 '733',
 '478',
 '493',
 '492',
 '292',
 '464',
 '582',
 '259',
 '473',
 '639',
 '412',
 '721',
 '562',
 '562',
 '862',
 '473',
 '222',
 '582',
 '952',
 '471',
 '641',
 '262',
 '475',
 '471',
 '561',
 '162',
 '181',
 '729',
 '471',
 '551',
 '561',
 '422',
 '465',
 '662',
 '467',
 '562',
 '479',
 '474',
 '649',
 '259',
 '107',
 '475',
 '478',
 '162',
 '902',
 '107',
 '181',
 '134',
 '562',
 '251',
 '561',
 '422',
 '320',
 '222',
 '339',
 '259',
 '844',
 '231',
 '463',
 '259',
 '181',
 '856',
 '478',
 '262',
 '141',
 '423',
 '681',
 '474',
 '424',
 '872',
 '383',
 '463',
 '467',
 '852',
 '478',
 '152',
 '463',
 '251',
 '851',
 '949',
 '529',
 '862',
 '969',
 '463',
 '181',
 '952',
 '641',
 '478',
 '471',
 '762',
 '331',
 '132',
 '452',
 '872',
 '107',
 '582',
 '478',
 '474',
 '855',
 '471',
 '222',
 '181',
 '181',
 '733',
 '682',
 '872',
 '682',
 '561',
 '272',
 '912',
 '471',
 '752',
 '649',
 '351',
 '465',
 '561',
 '478',
 '681',
 '582',
 '477',
 '472',
 '953',
 '204',
 '561',
 '681',
 '856',
 '181',
 '474',
 '221',
 '472',
 '759',
 '969',
 '649',
 '856',
 '291',
 '561',
 '242',
 '562',
 '473',
 '475',
 '715',
 '463',
 '259',
 '475',
 '251',
 '471',
 '961',
 '562',
 '961',
 '561',
 '969',
 '464',
 '741',
 '478',
 '204',
 '661',
 '471',
 '856',
 '681',
 '871',
 '682',
 '602',
 '452',
 '421',
 '472',
 '259',
 '465',
 '561',
 '471',
 '682',
 '856',
 '961',
 '949',
 '529',
 '682',
 '682',
 '682',
 '902',
 '464',
 '681',
 '222',
 '478',
 '465',
 '292',
 '251',
 '472',
 '472',
 '912',
 '872',
 '421',
 '463',
 '661',
 '682',
 '473',
 '681',
 '581',
 '478',
 '422',
 '856',
 '476',
 '562',
 '467',
 '259',
 '339',
 '852',
 '107',
 '561',
 '472',
 '478',
 '852',
 '475',
 '742',
 '144',
 '479',
 '562',
 '759',
 '551',
 '162',
 '478',
 '478',
 '463',
 '561',
 '872',
 '969',
 '562',
 '961',
 '682',
 '424',
 '682',
 '713',
 '682',
 '872',
 '474',
 '872',
 '465',
 '464',
 '476',
 '462',
 '872',
 '872',
 '474',
 '733',
 '961',
 '682',
 '561',
 '471',
 '620',
 '473',
 '763',
 '472',
 '465',
 '561',
 '491',
 '465',
 '953',
 '272',
 '561',
 '320',
 '561',
 '856',
 '467',
 '478',
 '102',
 '751',
 '961',
 '466',
 '561',
 '475',
 '421',
 '467',
 '661',
 '561',
 '681',
 '713',
 '911',
 '682',
 '259',
 '320',
 '466',
 '259',
 '271',
 '953',
 '464',
 '471',
 '465',
 '424',
 '292',
 '471',
 '561',
 '472',
 '855',
 '464',
 '857',
 '479',
 '872',
 '561',
 '426',
 '478',
 '462',
 '752',
 '478',
 '412',
 '465',
 '471',
 '465',
 '682',
 '172',
 '467',
 '562',
 '259',
 '653',
 '561',
 '862',
 '561',
 '561',
 '501',
 '561',
 '475',
 '872',
 '856',
 '424',
 '763',
 '473',
 '856',
 '561',
 '852',
 '953',
 '478',
 '422',
 '222',
 '856',
 '465',
 '561',
 '711',
 '132',
 '476',
 '733',
 '181',
 '478',
 '222',
 '463',
 '471',
 '463',
 '681',
 '259',
 '729',
 '259',
 '472',
 '478',
 '452',
 '856',
 '411',
 '911',
 '474',
 '232',
 '472',
 '474',
 '492',
 '463',
 '107',
 '478',
 '179',
 '291',
 '202',
 '478',
 '104',
 '464',
 '474',
 '478',
 '682',
 '465',
 '152',
 '474',
 '478',
 '181',
 '264',
 '681',
 '762',
 '612',
 '561',
 '467',
 '292',
 '941',
 '856',
 '463',
 '581',
 '651',
 '107',
 '969',
 '581',
 '855',
 '222',
 '474',
 '562',
 '465',
 '561',
 '862',
 '465',
 '862',
 '561',
 '463',
 '961',
 '479',
 '581',
 '259',
 '862',
 '424',
 '851',
 '107',
 '339',
 '732',
 '561',
 '474',
 '582',
 '464',
 '476',
 '682',
 '742',
 '742',
 '476',
 '521',
 '862',
 '856',
 '471',
 '713',
 '471',
 '961',
 '474',
 '494',
 '292',
 '464',
 '682',
 '478',
 '713',
 '424',
 '591',
 '474',
 '733',
 '561',
 '729',
 '842',
 '493',
 '473',
 '474',
 '107',
 '682',
 '424',
 '472',
 '465',
 '259',
 '721',
 '952',
 '712',
 '862',
 '961',
 '911',
 '561',
 '952',
 '478',
 '952',
 '949',
 '561',
 '423',
 '853',
 '561',
 '467',
 '141',
 '561',
 '475',
 '474',
 '752',
 '952',
 '467',
 '912',
 '463',
 '162',
 '423',
 '472',
 '463',
 '491',
 '107',
 '561',
 '291',
 '222',
 '471',
 '721',
 '721',
 '478',
 '721',
 '478',
 '471',
 '733',
 '561',
 '473',
 '969',
 '291',
 '682',
 '493',
 '421',
 '320',
 '181',
 '464',
 '961',
 '474',
 '472',
 '478',
 '264',
 '464',
 '141',
 '561',
 '351',
 '651',
 '952',
 '319',
 '476',
 '855',
 '856',
 '493',
 '561',
 '259',
 '466',
 '340',
 '476',
 '952',
 '961',
 '641',
 '561',
 '969',
 '475',
 '411',
 '465',
 '204',
 '320',
 '464',
 '561',
 '104',
 '423',
 '471',
 '912',
 '901',
 '411',
 '856',
 '949',
 '902',
 '465',
 '561',
 '311',
 '472',
 '751',
 '751',
 '471',
 '953',
 '172',
 '281',
 '856',
 '493',
 '473',
 '464',
 '733',
 '729',
 '856',
 '463',
 '424',
 '162',
 '466',
 '561',
 '452',
 '474',
 '474',
 '424',
 '591',
 '424',
 '562',
 '291',
 '421',
 '762',
 '591',
 '472',
 '855',
 '561',
 '152',
 '912',
 '561',
 '561',
 '949',
 '562',
 '161',
 '953',
 '423',
 '478',
 '759',
 '872',
 '649',
 '949',
 '251',
 '869',
 '862',
 '465',
 '901',
 '203',
 '292',
 '472',
 '462',
 '953',
 '862',
 '711',
 '474',
 '561',
 '292',
 '465',
 '952',
 '682',
 '562',
 '474',
 '562',
 ...]

In [10]:
len(answer)

100000

In [11]:
test["label"] = answer

In [12]:
test

,AI_id,digit_1,digit_2,digit_3,text_obj,text_mthd,text_deal,label
0,id_000001,NaN,NaN,NaN,치킨전문점에서,고객의주문에의해,치킨판매,561
1,id_000002,NaN,NaN,NaN,산업공구,다른 소매업자에게,철물 수공구,466
2,id_000003,NaN,NaN,NaN,절에서,신도을 대상으로,불교단체운영,949
3,id_000004,NaN,NaN,NaN,영업장에서,고객요구로,자동차튜닝,302
4,id_000005,NaN,NaN,NaN,실내포장마차에서,접객시설을 갖추고,"소주,맥주제공",562
...,...,...,...,...,...,...,...,...
99995,id_099996,NaN,NaN,NaN,사업장에서,일반인대상으로,버섯농장,472
99996,id_099997,NaN,NaN,NaN,한의원에서,외래환자위주고,치료,862
99997,id_099998,NaN,NaN,NaN,일반점포에서,소비자에게,그림판매,478
99998,id_099999,NaN,NaN,NaN,사업장에서,일반인.학생대상으로,학습공간제공,902
99999,id_100000,NaN,NaN,NaN,사업장에서,대리현대아파트를,관리,682

In [14]:
test.to_csv("ensemble_all_2.csv", index=False)

In [15]:
test = pd.read_csv("ensemble_all_2.csv")

In [16]:
test.count()

AI_id        100000
digit_1           0
digit_2           0
digit_3           0
text_obj      98189
text_mthd     97032
text_deal     93839
label        100000
dtype: int64

In [17]:
categories = {}
def set_keys(alpha, code_start, code_end):
  global categories
  for i in range(code_start, code_end+1):
    categories[i] = alpha

In [18]:
set_keys("A", 1,3)
set_keys("B", 5,8)
set_keys("C", 10,34)
set_keys("D", 35,35)
set_keys("E", 36,39)
set_keys("F", 41,42)
set_keys("G", 45,47)
set_keys("H", 49,52)
set_keys("I", 55,56)
set_keys("J", 58,63)
set_keys("K", 64,66)
set_keys("L", 68,68)
set_keys("M", 70,73)
set_keys("N", 74,76)
set_keys("O", 84,84)
set_keys("P", 85,85)
set_keys("Q", 86,87)
set_keys("R", 90,91)
set_keys("S", 94,96)
set_keys("T", 97,98)
set_keys("U", 99,99)

In [19]:
submission["digit_3"] = test["label"]
submission["digit_2"] = submission["digit_3"] // 10

In [20]:
for i in range(len(submission)):
  submission.loc[i,"digit_1"] = categories[submission.loc[i,"digit_2"]]
submission

           AI_id digit_1  digit_2  digit_3  text_obj   text_mthd text_deal
0      id_000001       I       56      561   치킨전문점에서    고객의주문에의해      치킨판매
1      id_000002       G       46      466      산업공구   다른 소매업자에게    철물 수공구
2      id_000003       S       94      949       절에서    신도을 대상으로    불교단체운영
3      id_000004       C       30      302     영업장에서       고객요구로     자동차튜닝
4      id_000005       I       56      562  실내포장마차에서   접객시설을 갖추고   소주,맥주제공
...          ...     ...      ...      ...       ...         ...       ...
99995  id_099996       G       47      472     사업장에서     일반인대상으로      버섯농장
99996  id_099997       Q       86      862     한의원에서     외래환자위주고        치료
99997  id_099998       G       47      478    일반점포에서       소비자에게      그림판매
99998  id_099999       R       90      902     사업장에서  일반인.학생대상으로    학습공간제공
99999  id_100000       L       68      682     사업장에서    대리현대아파트를        관리

[100000 rows x 7 columns]

In [21]:
submission.to_csv("ensemble_all_2.csv", index=False)